### ISSUE TITLE
Potential bug in demo?

### ISSUE THREAD

**Issue by fljot** [vicpenap/VPPDropDown#3]
Hello. Thank you for this library, currently using in one app prototyping — saved me some mind)

I'm having this kind of structure: 1st section — 1 regular row, 2nd section — regular row, then dropdown, then regular again.
So what I found is that when I expand dropdown "row" variable https://github.com/vicpenap/VPPDropDown/blob/master/VPPDropDownExample/DropDownExample.m#L213 becomes negative, so my labels are messed up. I'm in a hurry with this prototype, so I didn't go much into details, just set it back to 0 if it's negative — works in my particular case.

**Comment by vicpenap** [comment]
Yeah, in your particular case that instruction would be a bug. The correct solution, IMO, would be to handle normally all the cells before the (first) dropdown (because the cells' position will never be altered), then check with `VPPDropDown` if the `indexPath` is contained, and finally (after all the dropdowns) use the switch with the calculated row (the line #213 you linked).

Hope that helps for the future :)
